### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by alcazes** [adobe/aio-cli-plugin-console#96]
I have created an integration in Adobe I/O console for serverless integration. 

I have configured the aio console settings and I am able to retrieve all integrations using
`aio console list-integrations`

Against my integration Status is ENABLED

When I use 
`aio console select-integration 39610_86262`

I get this error:
`Error: Cannot retrieve integration: https://api.adobe.io/runtime/admin/namespaces/39610/86262 (500 Internal Server Error)`

In Adobe I/O console interface under Runtime if I click on "Enable serless actions" button I get this error:

> Argh, it seems that there was an error on our server.
> Definitely not our day. Can you try again later?
> ( request debug id: bpFGliDpEGywegJ8pYszSlOCyMMaCRko )

**Comment by meryllblanchet** [comment]
Hi @alcazes , thanks for reaching out.
I don't think the issue is related to the CLI or CLI Console plugin itself as it happens also on the Console side.

@mcorlan, do you have some more information about this issue?

**Comment by alcazes** [comment]
@meryllblanchet  Thanks for the update.

I am still facing issue and it does not seem Adobe support is able to fix the issue

**Comment by meryllblanchet** [comment]
@purplecabbage could I ask your feedback from a pure CLI/Console plugin perspective?

**Comment by mcorlan** [comment]
@alcazes We will be releasing a new version of Console in about a month. This will greatly improve the Runtime flows but still the CLI is the key for managing code. While waiting for the release, we should be focusing on the CLI. Thank you!

**Comment by alcazes** [comment]
@mcorlan Who would be the best team at Adobe to investigate the 500 internal server error that is returned to me ? Is there anything else you would need from me to speed up the process ?

**Comment by purplecabbage** [comment]
I can only guess, but It appears that the integration does not have the I/O Management API service attached.
You can try running `Debug=* aio console select-integration 39610_86262` and see if you get any more info in the verbose output.

**Comment by alcazes** [comment]
@purplecabbage I have checked in the Adobe I/O console integration and I/O Management API is there 
![image](https://user-images.githubusercontent.com/8456933/78225152-a725bd80-74c1-11ea-8c7e-8a076a1687f9.png)

**Comment by meryllblanchet** [comment]
@alcazes do you get more verbose output by running `Debug=* aio console select-integration 39610_86262` in your terminal?

**Comment by alcazes** [comment]
@meryllblanchet Sorry for the delay had to figure out how to use the Debug=* in Windows... 

Anyway here is the output with secret masked

````
set DEBUG=* & aio console select-integration 39610_86262
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\package.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\oclif.manifest.json +22ms
  @oclif/config:@adobe/aio-cli using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson C:\Users\User\AppData\Local\@adobe\aio-cli\package.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\package.json +3ms
  @oclif/config loading plugins [
  {
    name: '@adobe/aio-cli-plugin-runtime',
    tag: 'latest',
    type: 'user'
  }
] +15ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\package.json\package.json +20ms
  @oclif/config reading user plugin C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\package.json +22ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +23ms
  @oclif/config:@adobe/aio-cli-plugin-runtime using manifest from C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +0ms
  @oclif/config loading plugins [
  '@oclif/plugin-help',
  '@oclif/plugin-plugins',
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-not-found',
  '@adobe/aio-cli-plugin-config',
  '@adobe/aio-cli-plugin-jwt-auth',
  '@adobe/aio-cli-plugin-console',
  '@adobe/aio-cli-plugin-runtime',
  '@adobe/aio-cli-plugin-app',
  '@adobe/aio-cli-plugin-auth',
  '@adobe/aio-cli-plugin-certificate'
] +54ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help\package.json +206ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins\package.json +17ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth\package.json +0ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\package.json +0ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate\package.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found\oclif.manifest.json +82ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config\oclif.manifest.json +22ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete\oclif.manifest.json +17ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins\oclif.manifest.json +45ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\oclif.manifest.json +11ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help\oclif.manifest.json +53ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth\oclif.manifest.json +15ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth\oclif.manifest.json +39ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +93ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate\oclif.manifest.json +33ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app\oclif.manifest.json +31ms
  @oclif/config:@oclif/plugin-not-found using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-config using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config\oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-plugins using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins\oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-autocomplete using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete\oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-console using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-auth using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-jwt-auth using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-certificate using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-runtime using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-app using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app\oclif.manifest.json +0ms
  @oclif/config config done +677ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\package.json +50ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\oclif.manifest.json +2ms
  @oclif/config:@adobe/aio-cli using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\oclif.manifest.json +0ms
  @oclif/config reading user plugins pjson C:\Users\User\AppData\Local\@adobe\aio-cli\package.json +42ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\package.json +2ms
  @oclif/config loading plugins [
  {
    name: '@adobe/aio-cli-plugin-runtime',
    tag: 'latest',
    type: 'user'
  }
] +3ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\package.json\package.json +5ms
  @oclif/config reading user plugin C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\package.json +2ms
  @oclif/config loadJSON C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +2ms
  @oclif/config:@adobe/aio-cli-plugin-runtime using manifest from C:\Users\User\AppData\Local\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +0ms
  @oclif/config loading plugins [
  '@oclif/plugin-help',
  '@oclif/plugin-plugins',
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-not-found',
  '@adobe/aio-cli-plugin-config',
  '@adobe/aio-cli-plugin-jwt-auth',
  '@adobe/aio-cli-plugin-console',
  '@adobe/aio-cli-plugin-runtime',
  '@adobe/aio-cli-plugin-app',
  '@adobe/aio-cli-plugin-auth',
  '@adobe/aio-cli-plugin-certificate'
] +11ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help\package.json +8ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found\package.json +0ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\package.json +0ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth\package.json +1ms
  @oclif/config reading core plugin C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate\package.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete\oclif.manifest.json +2ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found\oclif.manifest.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins\oclif.manifest.json +1ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config\oclif.manifest.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth\oclif.manifest.json +1ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +1ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app\oclif.manifest.json +1ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help\oclif.manifest.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\oclif.manifest.json +1ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth\oclif.manifest.json +0ms
  @oclif/config loadJSON C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate\oclif.manifest.json +1ms  @oclif/config:@oclif/plugin-autocomplete using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-autocomplete\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-jwt-auth using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-jwt-auth\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-config using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config\oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-plugins using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-plugins\oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-help\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-app using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-app\oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-not-found using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\plugin-not-found\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-runtime using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-runtime\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-auth using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-auth\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-console using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\oclif.manifest.json +0ms
  @oclif/config:@adobe/aio-cli-plugin-certificate using manifest from C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-certificate\oclif.manifest.json +0ms
  @oclif/config config done +30ms
  @oclif/config start init hook +2ms
  aio:@adobe/aio-cli-plugin-config:hooks:init start C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-config\src\hooks.js +0ms
  aio-cli-config reading config: C:\Users\User\.config\aio +0ms
  aio-cli-config reading config: C:\Users\User\.aio +17ms
  aio-cli-plugin-conf {
  aio-cli-plugin-conf   jwt-auth: {
  aio-cli-plugin-conf     client_id: "[REPLACED]",
  aio-cli-plugin-conf     client_secret: ""[REPLACED]",
  aio-cli-plugin-conf     jwt_payload: {
  aio-cli-plugin-conf       exp: "[REPLACED],
  aio-cli-plugin-conf       iss: ""[REPLACED]",
  aio-cli-plugin-conf       sub: ""[REPLACED]",
  aio-cli-plugin-conf       "https://ims-na1.adobelogin.com/s/ent_adobeio_sdk": true,
  aio-cli-plugin-conf       aud: "https://ims-na1.adobelogin.com/c/"[REPLACED]"
  aio-cli-plugin-conf     },
  aio-cli-plugin-conf     token_exchange_url: "https://ims-na1.adobelogin.com/ims/exchange/jwt",
  aio-cli-plugin-conf     console_get_orgs_url: "https://api.adobe.io/console/organizations",
  aio-cli-plugin-conf     console_get_namespaces_url: "https://api.adobe.io/runtime/admin/namespaces/",
  aio-cli-plugin-conf     jwt_private_key: ""[REPLACED]",
  aio-cli-plugin-conf     access_token: ""[REPLACED]",
  aio-cli-plugin-conf     access_token_expiry: "Fri Apr 03 2020 09:05:02 GMT+0100 (British Summer Time)",
  aio-cli-plugin-conf     pk_checksum: ""[REPLACED]"
  aio-cli-plugin-conf   }
  aio-cli-plugin-conf } +0ms
  aio:@adobe/aio-cli-plugin-config:hooks:init done +4s
  @oclif/config init hook done +4s
  aio init version: @oclif/command@1.5.19 argv: [ 'console:select-integration', '39610_86262' ] +0ms
  @oclif/config runCommand console:select-integration [ '39610_86262' ] +96ms
  @oclif/config:@adobe/aio-cli-plugin-console require C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\src\commands\console\select-integration.js +4s
  @oclif/config start prerun hook +3s
  @oclif/config prerun hook done +1ms
  aio:console:select-integration init version: @oclif/command@1.5.19 argv: [ '39610_86262' ] +0ms
  aio-cli-plugin-console:select-integration _selectIntegration integrationId 39610_86262 +0ms
  aio-cli-plugin-jwt-auth JWT Config: {
  orgId: '"[REPLACED]',
  technicalAccountId: '"[REPLACED]',
  clientId: '"[REPLACED]',
  clientSecret: '"[REPLACED]b',
  ims: 'https://ims-na1.adobelogin.com',
  metaScopes: [ 'https://ims-na1.adobelogin.com/s/ent_adobeio_sdk' ],
  privateKey: '"[REPLACED]'
} +0ms
  aio-cli-plugin-jwt-auth token is expired +0ms
  aio-cli-plugin-jwt-auth getting a new token +1ms
  aio-cli-config writing config: jwt-auth.access_token at C:\Users\User\.config\aio +4s
  aio-cli-config reading config: C:\Users\User\.config\aio +3ms
  aio-cli-config reading config: C:\Users\User\.aio +2ms
  aio-cli-config writing config: jwt-auth.access_token_expiry at C:\Users\User\.config\aio +0ms
  aio-cli-config reading config: C:\Users\User\.config\aio +2ms
  aio-cli-config reading config: C:\Users\User\.aio +2ms
  aio-cli-config writing config: jwt-auth.pk_checksum at C:\Users\User\.config\aio +1ms
  aio-cli-config reading config: C:\Users\User\.config\aio +1ms
  aio-cli-config reading config: C:\Users\User\.aio +14ms
  aio-cli-plugin-console:select-integration calling with options: {
  headers: {
    'X-Api-Key': '"[REPLACED]',
    'x-ims-org-id': '"[REPLACED]',
    Authorization: 'Bearer "[REPLACED]',
    accept: 'application/json'
  }
} +659ms
  aio-cli-plugin-console fetch: https://api.adobe.io/runtime/admin/namespaces/39610/86262 +0ms
  aio-cli-plugin-console fetch options: {
  aio-cli-plugin-console   "headers": {
  aio-cli-plugin-console     "X-Api-Key": ""[REPLACED]",
  aio-cli-plugin-console     "x-ims-org-id": ""[REPLACED]",
  aio-cli-plugin-console     "Authorization": "Bearer "[REPLACED]",
  aio-cli-plugin-console     "accept": "application/json"
  aio-cli-plugin-console   }
  aio-cli-plugin-console } +0ms
  aio-cli-plugin-console:select-integration Error: Cannot retrieve integration: https://api.adobe.io/runtime/admin/namespaces/39610/86262 (500 Internal Server Error)
  aio-cli-plugin-console:select-integration     at _selectIntegration (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\src\commands\console\select-integration.js:59:11)
  aio-cli-plugin-console:select-integration     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  aio-cli-plugin-console:select-integration     at async SelectIntegrationCommand.run (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\src\commands\console\select-integration.js:97:16)
  aio-cli-plugin-console:select-integration     at async SelectIntegrationCommand._run (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\command\lib\command.js:44:20)
  aio-cli-plugin-console:select-integration     at async Config.runCommand (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\config\lib\config.js:160:9)
  aio-cli-plugin-console:select-integration     at async Main.run (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\command\lib\main.js:21:9)
  aio-cli-plugin-console:select-integration     at async Main._run (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\command\lib\command.js:44:20) +884ms
Error: Cannot retrieve integration: https://api.adobe.io/runtime/admin/namespaces/39610/86262 (500 Internal Server Error)
    at Object.error (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\errors\lib\index.js:22:17)
    at SelectIntegrationCommand.error (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@oclif\command\lib\command.js:57:23)
    at SelectIntegrationCommand.run (C:\Users\User\AppData\Roaming\npm\node_modules\@adobe\aio-cli\node_modules\@adobe\aio-cli-plugin-console\src\commands\console\select-integration.js:100:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
````

Hope this helps

**Comment by meryllblanchet** [comment]
Thanks @alcazes ! We'll come back to you later in the afternoon.
cc @mcorlan @purplecabbage

**Comment by mcorlan** [comment]
@alcazes Can you try again the flow for "39610_86262"? I fixed the namespace error in our system for "39610_86262". 
Until we release the new version later this month, we will need to fix the issues manually. 

If this doesn't work, please open a support ticket and add me or Meryll to the ticket as contact persons and we will send you the credentials.

Thank you and sorry again for the inconvenience.

**Comment by alcazes** [comment]
@mcorlan I am still getting same error I will add you to existing support ticket I have with clientcare

**Comment by meryllblanchet** [comment]
Closing the issue as we have been following-up directly with @alcazes .
